FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY --from=build /app/.output /app/.output
COPY --from=build /app/package*.json ./
RUN npm install --omit=dev
ENV HOST=0.0.0.0
ENV PORT=3010
EXPOSE 3010
CMD ["node", ".output/server/index.mjs"]
